name: delforte
description: "Delforte app"
version: 1.0.0+1
environment:
  sdk: ^3.11.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  pdf: ^3.11.3
  sqlite3: ^2.9.4
  sqlite3_flutter_libs: ^0.5.40

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
