name: delforte
description: "Delforte app"
version: 1.0.0+3
environment:
  sdk: 3.11.1

dependencies:
  characters: 1.4.1
  cupertino_icons: 1.0.8
  file_picker: 11.0.2
  flutter:
    sdk: flutter
  image_picker: 1.1.2
  path_provider: 2.1.5
  pdf: 3.11.3
  printing: 5.13.4
  sqlite3: 3.3.1
  sqlite3_flutter_libs: 0.6.0+eol

dev_dependencies:
  flutter_lints: 6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/DMSans-Regular.ttf
    - assets/fonts/DMSans-SemiBold.ttf
    - assets/fonts/DMSans-Bold.ttf
    - assets/fonts/DMMono-Regular.ttf
    - assets/fonts/DMMono-Medium.ttf
  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/DMSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
    - family: DM Mono
      fonts:
        - asset: assets/fonts/DMMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/DMMono-Medium.ttf
          weight: 500
